name = "gruvbox"

[colors]
bg = "#282828"
fg = "#ebdbb2"
gutter = "#665c54"
cursor_bg = "#ebdbb2"
cursor_fg = "#282828"
selection = "#3c3836"
statusbar_bg = "#1d2021"
statusbar_fg = "#ebdbb2"
keyword = "#fb4934"
string = "#b8bb26"
comment = "#928374"
function = "#fabd2f"
type = "#83a598"
number = "#d3869b"
operator = "#fe8019"
property = "#8ec07c"
heading_1 = "#fabd2f"
heading_2 = "#fb4934"
heading_3 = "#b8bb26"
heading_4 = "#8ec07c"
heading_5 = "#83a598"
heading_6 = "#d3869b"
link = "#83a598"
quote_marker = "#928374"
quote_text = "#ebdbb2"
code_bg = "#1d2021"
code_border = "#3c3836"
table_border = "#3c3836"
table_header_fg = "#fabd2f"
hr = "#3c3836"
task_done = "#b8bb26"
task_pending = "#fabd2f"
mermaid_caption = "#a89984"
search_match = "#fe8019"
popup_bg = "#1d2021"
popup_border = "#3c3836"
popup_selected = "#3c3836"
popup_dim = "#928374"
popup_accent = "#fabd2f"
